---
title: "LMM considerations"
output:
  html_document:
    df_print: paged
---

# One factor rm ANOVA
```{r message=FALSE, warning=FALSE, include=FALSE}
library(lme4)
library(afex)
library(ggplot2)

## one factor
df1 <- read.csv2("one_factor_rm.csv", header=T,dec=",")
```
```{r}
### fixed effect, random intercept
model_fe <- lmer(delta_distance ~ acceleration + (1|id),df1)
summary(model_fe)
```


```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
### fixed effect, random intercept & slope
# rescale predictor (otherwise conversion warning)
mu_x <- mean(df1$acceleration)
sig_x <- sd(df1$acceleration)
df1$acceleration_s <- (df1$acceleration-mu_x)/sig_x # standardize predictor
```
```{r}
model <- lmer(delta_distance ~ acceleration_s + (1+acceleration_s|id),df1)
summary(model)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
#### PLOTS ####
model_ns <- lmer(delta_distance ~ acceleration + (1+acceleration|id),df1)
# df$acceleration2 <- df$acceleration
# df$acceleration <- factor(df$acceleration, labels=c("424.62","607.39","780.3","1165"))
# plot_model <- lm(delta_distance ~ acceleration,df)
# predicted_df <- predict.lm(plot_model,df$predicted)

df1$id <- factor(df1$id)

## convert slope and intercept to original scale
# convert intercept (fixed) to original scale
fixef(model)[1] - fixef(model)[2]*mu_x/sig_x 
# compare with this value (from model fit on original values)
fixef(model_ns)[1] 

# convert individual random slopes
rnd_slopes_2 <- (fixef(model)[2] + ranef(model)$id[,2])/sig_x
# reference values from model fit on original values
rnd_slopes_1 <- fixef(model_ns)[2] + ranef(model_ns)$id[,2] 
#test
rnd_slopes_2 - rnd_slopes_1
plot(rnd_slopes_1, rnd_slopes_2); abline(a=0,b=1,lty=2)

# convert individual random intercepts
rnd_int_2 <- (fixef(model)[1] + ranef(model)$id[,1]) - (fixef(model)[2] + ranef(model)$id[,2])*mu_x/sig_x
# reference values from model fit on original values
rnd_int_1 <- fixef(model_ns)[1] + ranef(model_ns)$id[,1] 
#test
rnd_int_2 - rnd_int_1
plot(rnd_int_1, rnd_int_2); abline(a=0,b=1,lty=2)

intercepts <- rnd_int_2
slopes <- rnd_slopes_2

###
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
p <- ggplot(df1, aes(x=acceleration,y=delta_distance))+
  ylab("Change in distance [mm/s]")+
  xlab("Acceleration [mm/s²]")+
  # geom_line()+
  geom_point(alpha=.65)+
  # geom_jitter(width=0.4)+
  geom_abline(slope=slopes, intercept=intercepts,alpha=.3)+
  # geom_line(aes(x=df$acceleration,y=predicted_df),size=1,color="black")+
  geom_abline(slope=mean(slopes), intercept=mean(intercepts),size=1.5,color="black")+
  theme_bw()+
  scale_x_continuous(limits = c(400,1200))+
  theme(legend.position="none",
        panel.grid.major = element_line(color = "white"), 
        panel.grid.minor = element_line(color = "white"),
        text=element_text(size=12,color="black")
        )
p
```






# three factor mixed anova
Load data + packages:

```{r}
df <- read.csv2("lmm.csv", header=T,dec=",")

library(lme4)
library(afex)
```

Fit model:

model <- lmer(dv ~ group+age_group+stage)
summary(model)